# fly.toml app configuration file generated for stormtracker on 2024-12-02T01:08:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stormtracker'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
